### ISSUE TITLE
Design Review Call: Simple Crypto: Master Bitcoin

### ISSUE THREAD

**Issue by yfrbl** [BitcoinDesign/Meta#472] opened 2023-01-30 14:14 UTC
```meta
UTCTime: 2023-02-13 16:00 UTC
Duration: 1h
```

![alt text](https://simple-crypto-bucket.s3.eu-central-1.amazonaws.com/banner_b65647977a.jpeg "")

### Agenda

We'll discuss the user experience of [Simple Crypto: Master Bitcoin](https://www.simple-crypto.app/). If possible, please download and try out the app in advance and come prepared with notes.

### Check your timezone

[https://everytimezone.com/s/2ba1c71e](https://everytimezone.com/s/2ba1c71e)

### Join the call

[https://meet.jit.si/bitcoindesign](https://meet.jit.si/bitcoindesign)

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by danielnordh** [comment] 2023-02-13 10:11
Will try to join but unfortunately it is during my school run to get the kids.
In case I don't manage to give the feedback live, here are my notes:

- Nice friendly design
- Great use of illustrations and subtle animations 
- Clear structure, easy to orient and navigate
- Overall effective in education about bitcoin

Some thoughts I had a long the way, I'm sharing to help, not to discourage!
- App asks for notification permission on launch, even before seeing the app logo etc, this will generally lead to a lot of people declining. Better to ask in relation to a clear purpose with benefit for the user.
- The onboarding screens are nice, but 6 feels like a few too many, people want to 'enter the app' a.s.a.p. The first two are almost enough IMO.
- Certification, feels somewhat weird given bitcoin's freedom/authority scepticism. Why would I want it, what does it get me ?
- Some crypto lingo is probably weird to non-bitcoiners - "Be Financial Sovereign"
- Ads, especially for other financial services strongly affected my respect for the app, especially when it talks about scams and I wonder if the revenue here is worth that loss.
- I could not avoid seeing the ads full screen at the end of chapters/quizzes, even when tapping the app's own Continue button. Maybe that is by design, but it felt unexpected as I did not tap on the add itself.
- Getting sats sounds cool, and the game element of spinning is fun. Did not want to Login however so skipped that part (unclear what else I would gain from logging in to an educational app)
- Translations can be improved here and there, one example - "Write us a email"
- Chapter / Quiz tooltip screen did not appear first two times I took quizzes (as I skipped straight to the quiz), but it did on the third chapter
- Not an issue really, but noticed that some chapters let me see the index and select sub-chapters while some jumped straight into the full screen modals. I now understand that it's probably because the latter are shorter.
- In the wallet chapter, one question is about where keys should be kept (with the answer being offline). This isn't always feasible or realistic for mobile/daily/lightning wallets so some nuance could be useful. (Which is safer...)
- In Alternatives, I wonder if this chapter is really necessary. Kudos for being pretty neutral on Ethereum and Monero.
- "Since the stock is modifiable ether is also not a hard currency" - is probably incomprehensible to most people
- Why include Tether when text clearly points to it being shady / scammy?
- The recommendation to be aware of scams is well meant, but the information contained isn't very practical and may just scare people. How do I recognise a scam etc.
- My recommendation would be to just talk about bitcoin, positively, and not worry about alternatives and scams at it may stimulate more interest/uncertainty than just focusing on building positivity around bitcoin.
- Since the app is 95% about bitcoin, the name Simple Crypto is a little bit of a surprise, search term optimisation?

Use with your own judgment, or feel free to ignore :)

**Comment by GBKS** [comment] 2023-02-14 07:00
That was a great conversation, thanks to all who participated. The team hopefully now has some helpful and practical feedback to consider, and it will be interesting to observe how the app changes. Call recordings are now up on [BitcoinTV](https://bitcointv.com/w/4gzmUmiwWWGort3BzCXKhm) and [YouTube](https://youtu.be/qmMlp1b9WXw). And here's [a link to the Figma file](https://www.figma.com/file/Tbn9hFUeirowmLItk1hZ4i/Simple-Crypto-app-review-230213?node-id=0%3A1&t=ClQumbPMoP82kU6r-1) with screenshots that used during the call.

**Closed by GBKS** 2023-02-14 07:00 UTC
Labels: call

**Comment by yfrbl** [comment] 2023-02-14 09:08
Hi Daniel,

Thank you so much for taking the time to write us such detailed feedback!

> * App asks for notification permission on launch, even before seeing the app logo etc, this will generally lead to a lot of people declining. Better to ask in relation to a clear purpose with benefit for the user.

That's a good point, we will configure so that it is delayed to the back. Push notifications are mostly used to send daily quotes, but we can and will also use the feature to motivate users for more content. 

> * The onboarding screens are nice, but 6 feels like a few too many, people want to 'enter the app' a.s.a.p. The first two are almost enough IMO.

I changed that, but in my opinion two are not enough, it will be about four. At the bottom left, there is also the option to skip the onboarding directly. 

> * Certification, feels somewhat weird given bitcoin's freedom/authority scepticism. Why would I want it, what does it get me ?

The certificate serves as an incentive and perk for the user to complete the entire course content. We have actually found that it spurs user motivation. I also talked about this in the review call.

> * App (on iOS) seem to play sounds even when set to silent mode

Thx, will be fixed!

> * Ads, especially for other financial services strongly affected my respect for the app, especially when it talks about scams and I wonder if the revenue here is worth that loss.

I see your point! In the future we will select our ad partners so that we can (hopefully) filter irrelevant ones.

> * Getting sats sounds cool, and the game element of spinning is fun. Did not want to Login however so skipped that part (unclear what else I would gain from logging in to an educational app)

The login serves two purposes. On the one hand, it prevents users from taking advantage of us and paying out a disproportionate amount of sats per user. On the other hand, it serves as a basis for further interaction (via mail) and personalization of the learning experience. (on our roadmap)

> * Translations can be improved here and there, one example - "Write us a email"

Yeah, we are not native speakers. We would appreciate it if anyone would like to work with us to improve the translations. This also applies to other languages! Currently German, English and Spanish are available. 

> * Chapter / Quiz tooltip screen did not appear first two times I took quizzes (as I skipped straight to the quiz), but it did on the third chapter

thx, noted.

> * In the wallet chapter, one question is about where keys should be kept (with the answer being offline). This isn't always feasible or realistic for mobile/daily/lightning wallets so some nuance could be useful. (Which is safer...)

I agree, changed!

> * In Alternatives, I wonder if this chapter is really necessary. Kudos for being pretty neutral on Ethereum and Monero.
> * "Since the stock is modifiable ether is also not a hard currency" - is probably incomprehensible to most people
> * Why include Tether when text clearly points to it being shady / scammy?
> * The recommendation to be aware of scams is well meant, but the information contained isn't very practical and may just scare people. How do I recognise a scam etc.
> * My recommendation would be to just talk about bitcoin, positively, and not worry about alternatives and scams at it may stimulate more interest/uncertainty than just focusing on building positivity around bitcoin.

We mainly offer Bitcoin content, but newbies coming into the space want to be informed "holistically" first. Simply telling them not to bother with the other things would not solve the problem. Instead, we want to provide them with information that empowers them to make their own decisions. I also agree with you that the content here can be improved.
